=== Jepp0103/Java_User_Driven_Acceptance_Testing_Mandatory_2/Mandatory2/ATDD.dtd
<!ATTLIST shipitem story CDATA #FIXED "1">
 	
 	<!ATTLIST ordermaterials story CDATA #FIXED "2">
 	
 	<!ATTLIST queryitems story CDATA #FIXED "3">
	
	<!ELEMENT testcases  (shipitem*,ordermaterials*,queryitems*) >
	
	<!ELEMENT shipitem (given+,when+,item,address,item?,then+,address?)>

	<!ELEMENT ordermaterials (given+,when+,material+,then+)>
	
	<!ELEMENT queryitems (given+,when+,item,then+)>
	
	

	
   	<!ELEMENT given (#PCDATA)>
	<!ELEMENT when (#PCDATA)>
	<!ELEMENT then (#PCDATA)>
   	<!ELEMENT item (#PCDATA)>
   	<!ELEMENT address (#PCDATA)>
   	<!ELEMENT material (#PCDATA)>

=== Jepp0103/Java_User_Driven_Acceptance_Testing_Mandatory_2/Mandatory2/Story2.xml
<?xml version = "1.0" ?>	
	
<!DOCTYPE testcases SYSTEM "ATDD.dtd"[
	<!ENTITY % story1   "IGNORE">
	<!ENTITY % story2 "INCLUDE">
	]>
	
	<testcases>
		<testcase story="2">
			<given>Said materials are not in stock </given>
			<when>Actor ordering materials </when>
			<item>Lenovo laptop </item>
			<address>København </address>
			<then>Shipping is not authorized. No actions taken </then>
		</testcase>
		
		<testcase story="2">
			<given>Depot of given item type is not empty </given>
			<when>Actor is Shipping </when>
			<item>Lenovo laptop </item>
			<address>København </address>
			<item>Lenovo </item>
			<then> is shipped to </then>
			<address>København </address>			
		</testcase>
		

	
	</testcases>

=== Jepp0103/Java_User_Driven_Acceptance_Testing_Mandatory_2/Mandatory2/kak.xml
<?xml version = "1.0" ?>	
	
<!DOCTYPE testcases SYSTEM "ATDD.dtd">
	<testcases>

		<story1case>
			<given>depot of given item type is empty</given>
			<when>actor is Shipping</when>
			<item>Iphone</item>
			<address>København</address>
			<then>shipping is not authorized. No actions taken</then>
		</story1case>
		
		<story1case>
			<given>depot of given item type is not empty</given>
			<when>actor is Shipping</when>
			<item>Iphone</item>
			<address>København</address>
			<item>Iphone</item>
			<then> is shipped to</then>
			<address>København</address>			
		</story1case>
		
		<story2case >
			<given>said materials are not in stock</given>
			<when>actor orders materials:</when>
			<material>screws</material>
			<material>hinges</material>	
			<then>order is not placed </then>		
		</story2case>
		
		<story2case>
			<given>said materials are in stock</given>
			<when>actor orders materials:</when>
			<material>screws</material>
			<material>hinges</material>
			<then>order for material is placed </then>
		</story2case>
		

	
	</testcases>
